resources:
  containers:
    - container: node
      image: node:10

jobs:
  - job: build
    container: node
    steps:
      - checkout: self
        clean: true
        displayName: Checkout source
      - script: yarn config set unsafe-perm true
        displayName: Set Unsafe Perms for Yarn
      - script: yarn install --frozen-lockfile
        displayName: Install using yarn with the lockfile frozen
      - script: yarn run lerna bootstrap
        displayName: Bootstrap with lerna
  - job: publish
    dependsOn: build
    container: node
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - checkout: none
      - script: echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > ~/.npmrc
        displayName: Fill in auth token for NPMJS
      - script: yarn config set unsafe-perm true
        displayName: Set Unsafe Perms for Yarn
      - script: yarn install --frozen-lockfile
        displayName: Install using yarn with the lockfile frozen
      - script: yarn run lerna publish from-package --no-git-reset
        displayName: Publish to NPMJS
  - job: ghpages
    dependsOn: publish
    container: node
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    steps:
      - task: InstallSSHKey@0
        inputs:
          hostName: $(knownHosts)
          sshPublicKey: $(publicKey)
          sshKeySecureFile: id_github
      - script: yarn config set unsafe-perm true
        displayName: Set Unsafe Perms for Yarn
      - script: yarn install --frozen-lockfile
        displayName: Install using yarn with the lockfile frozen
      - script: yarn run lerna bootstrap --scope @ukho/design-system
        displayName: Bootstrap with lerna - Scoped to @ukho/design-system
      - script: |
          cd projects/site
          yarn add -D gh-pages@2.0.1
          git config user.email "pipeline@ukho.gov.uk"
          git config user.name "Azure Pipeline"
          touch dist/.nojekyll
          echo "design.ukho.dev" > dist/CNAME
          yarn run gh-pages --dotfiles --message "[skip ci] gh-pages update" --dist dist -r git@github.com:UKHO/design-system.git
