resources:
  containers:
    - container: node
      image: node:10

jobs:
- job: build_lib
  container: node
  steps:
    - checkout: self
      clean: true
    - script: yarn install
    - script: yarn run ng build @ukho/components
- job: build_site
  container: node
  steps:
    - checkout: self
      clean: true
    - script: yarn install
    - script: |
        cd projects/site
        yarn run build
    - publish: projects/site/dist
      artifact: site
- job: ghpages
  dependsOn: build_site
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  container: node
  steps:
  - download: current
    artifact: site
  - task: InstallSSHKey@0
    inputs:
      hostName: $(knownHosts)
      sshPublicKey: $(publicKey)
      sshKeySecureFile: id_github
  - script: |
      touch dist/.nojekyll
      echo "design.ukho.dev" > dist/CNAME
      npm install --save-dev gh-pages@2.0.1
      git config user.email "pipeline@ukho.gov.uk"
      git config user.name "Azure Pipeline"
  - script: $(npm bin)/gh-pages --dotfiles --message "[skip ci] gh-pages update" --dist projects/site/dist -r git@github.com:UKHO/design-system.git
