/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdmiraltyDialogue {
        /**
          * The heading to display.
         */
        "heading": string;
        /**
          * The role to give the dialogue section. Set this to `alert` if the dialogue box is being used to summarise error messages.
         */
        "sectionRole": 'alert';
        /**
          * The type of dialogue box to render.
         */
        "type": 'info' | 'warning' | 'success' | 'error';
    }
}
declare global {
    interface HTMLAdmiraltyDialogueElement extends Components.AdmiraltyDialogue, HTMLStencilElement {
    }
    var HTMLAdmiraltyDialogueElement: {
        prototype: HTMLAdmiraltyDialogueElement;
        new (): HTMLAdmiraltyDialogueElement;
    };
    interface HTMLElementTagNameMap {
        "admiralty-dialogue": HTMLAdmiraltyDialogueElement;
    }
}
declare namespace LocalJSX {
    interface AdmiraltyDialogue {
        /**
          * The heading to display.
         */
        "heading"?: string;
        /**
          * The role to give the dialogue section. Set this to `alert` if the dialogue box is being used to summarise error messages.
         */
        "sectionRole"?: 'alert';
        /**
          * The type of dialogue box to render.
         */
        "type"?: 'info' | 'warning' | 'success' | 'error';
    }
    interface IntrinsicElements {
        "admiralty-dialogue": AdmiraltyDialogue;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "admiralty-dialogue": LocalJSX.AdmiraltyDialogue & JSXBase.HTMLAttributes<HTMLAdmiraltyDialogueElement>;
        }
    }
}
