import styles from "./styles.module.css";
import {
  AdmiraltyTable, AdmiraltyTableBody, AdmiraltyTableCell,
  AdmiraltyTableHeader,
  AdmiraltyTableHeaderCell,
  AdmiraltyTableRow,
} from "@ukho/admiralty-react/dist";

export default function SpacingVariables() {
  return (
    <div className={styles.spacingVariablesTable}>
      <AdmiraltyTable>
        <AdmiraltyTableHeader>
          <AdmiraltyTableRow>
            <AdmiraltyTableHeaderCell>Variable</AdmiraltyTableHeaderCell>
            <AdmiraltyTableHeaderCell>Rem</AdmiraltyTableHeaderCell>
            <AdmiraltyTableHeaderCell>Px</AdmiraltyTableHeaderCell>
          </AdmiraltyTableRow>
        </AdmiraltyTableHeader>
        <AdmiraltyTableBody>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-0</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>0</AdmiraltyTableCell>
            <AdmiraltyTableCell>0</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-1</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>0.3</AdmiraltyTableCell>
            <AdmiraltyTableCell>4</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-2</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>0.5</AdmiraltyTableCell>
            <AdmiraltyTableCell>8</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-3</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>0.8</AdmiraltyTableCell>
            <AdmiraltyTableCell>12</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-4</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1</AdmiraltyTableCell>
            <AdmiraltyTableCell>16</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-5</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1.3</AdmiraltyTableCell>
            <AdmiraltyTableCell>20</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code> --admiralty-spacing-6</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1.5</AdmiraltyTableCell>
            <AdmiraltyTableCell>24</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-7</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1.8</AdmiraltyTableCell>
            <AdmiraltyTableCell>28</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-8</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>2</AdmiraltyTableCell>
            <AdmiraltyTableCell>32</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-6</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>2.75</AdmiraltyTableCell>
            <AdmiraltyTableCell>44</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-auto</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>auto</AdmiraltyTableCell>
            <AdmiraltyTableCell>auto</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-unset</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>unset</AdmiraltyTableCell>
            <AdmiraltyTableCell>unset</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-spacing-inherit</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>inherit</AdmiraltyTableCell>
            <AdmiraltyTableCell>inherit</AdmiraltyTableCell>
          </AdmiraltyTableRow>
        </AdmiraltyTableBody>
      </AdmiraltyTable>
    </div>
  );
}
