import styles from "./styles.module.css";
import {
  AdmiraltyTable, AdmiraltyTableBody, AdmiraltyTableCell,
  AdmiraltyTableHeader,
  AdmiraltyTableHeaderCell,
  AdmiraltyTableRow,
} from "@ukho/admiralty-react/dist";

export default function TypographicScaleVariables() {
  return (
    <div className={styles.typographicScaleVariablesTable}>
      <AdmiraltyTable>
        <AdmiraltyTableHeader>
          <AdmiraltyTableRow>
            <AdmiraltyTableHeaderCell>Variable</AdmiraltyTableHeaderCell>
            <AdmiraltyTableHeaderCell>Rem</AdmiraltyTableHeaderCell>
            <AdmiraltyTableHeaderCell>Px</AdmiraltyTableHeaderCell>
          </AdmiraltyTableRow>
        </AdmiraltyTableHeader>
        <AdmiraltyTableBody>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size--3</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>0.688</AdmiraltyTableCell>
            <AdmiraltyTableCell>11.008</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size--2</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>0.75</AdmiraltyTableCell>
            <AdmiraltyTableCell>12</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size--1</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>0.875</AdmiraltyTableCell>
            <AdmiraltyTableCell>14</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size--0</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1</AdmiraltyTableCell>
            <AdmiraltyTableCell>16</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-1</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1.375</AdmiraltyTableCell>
            <AdmiraltyTableCell>22</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-2</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1.5</AdmiraltyTableCell>
            <AdmiraltyTableCell>24</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-3</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>1.75</AdmiraltyTableCell>
            <AdmiraltyTableCell>28</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-4</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>2</AdmiraltyTableCell>
            <AdmiraltyTableCell>32</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-5</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>2.25</AdmiraltyTableCell>
            <AdmiraltyTableCell>36</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-6</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>2.75</AdmiraltyTableCell>
            <AdmiraltyTableCell>44</AdmiraltyTableCell>
          </AdmiraltyTableRow>
          <AdmiraltyTableRow>
            <AdmiraltyTableCell>
              <code>--admiralty-font-size-7</code>
            </AdmiraltyTableCell>
            <AdmiraltyTableCell>3.5</AdmiraltyTableCell>
            <AdmiraltyTableCell>56</AdmiraltyTableCell>
          </AdmiraltyTableRow>
        </AdmiraltyTableBody>
      </AdmiraltyTable>
    </div>
  );
}
