
import * as d from './components';

export const DIRECTIVES = [
  d.AdmiraltyBreadcrumb,
  d.AdmiraltyBreadcrumbs,
  d.AdmiraltyButton,
  d.AdmiraltyCard,
  d.AdmiraltyCheckbox,
  d.AdmiraltyColourBlock,
  d.AdmiraltyDialogue,
  d.AdmiraltyExpansion,
  d.AdmiraltyFileInput,
  d.AdmiraltyFilter,
  d.AdmiraltyFilterGroup,
  d.AdmiraltyFooter,
  d.AdmiraltyHeader,
  d.AdmiraltyHeaderMenuItem,
  d.AdmiraltyHeaderProfile,
  d.AdmiraltyHeaderSubMenuItem,
  d.AdmiraltyHint,
  d.AdmiraltyHr,
  d.AdmiraltyIcon,
  d.AdmiraltyInput,
  d.AdmiraltyInputError,
  d.AdmiraltyLabel,
  d.AdmiraltyLink,
  d.AdmiraltyPaginator,
  d.AdmiraltyPhaseBanner,
  d.AdmiraltyProgressBar,
  d.AdmiraltyRadio,
  d.AdmiraltyRadioGroup,
  d.AdmiraltySelect,
  d.AdmiraltySideNav,
  d.AdmiraltySideNavItem,
  d.AdmiraltyTable,
  d.AdmiraltyTableBody,
  d.AdmiraltyTableCell,
  d.AdmiraltyTableHeader,
  d.AdmiraltyTableHeaderCell,
  d.AdmiraltyTableRow,
  d.AdmiraltyTextarea,
  d.AdmiraltyTypeAhead,
  d.AdmiraltyTypeAheadItem
];
