module.exports = {
  //stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  stories: ['../src/components/button/button.stories.ts',
  '../src/components/breadcrumb/breadcrumb.stories.ts',
  '../src/components/breadcrumbs/breadcrumbs.stories.ts',
  '../src/components/card/card.stories.ts',
  '../src/components/checkbox/checkbox.stories.ts',
  '../src/components/colour-block/colour-block.stories.ts',
  '../src/components/dialogue/dialogue.stories.ts',
  '../src/components/expansion/expansion.stories.ts',
  '../src/components/file-input/file-input.stories.ts',
  '../src/components/filter/filter.stories.ts',
  '../src/components/footer/footer.stories.ts',
  '../src/components/header/header.stories.ts',
  '../src/components/hint/hint.stories.ts',
  '../src/components/horizontal-rule/horizontal-rule.stories.ts',
  '../src/components/icon/icon.stories.ts',
  '../src/components/input/input.stories.ts',
  '../src/components/input-error/input-error.stories.ts',
  '../src/components/label/label.stories.ts',
  '../src/components/link/link.stories.ts',
  '../src/components/paginator/paginator.stories.ts',
  '../src/components/phase-banner/phase-banner.stories.ts',
  '../src/components/progress-bar/progress-bar.stories.ts',
  '../src/components/radio/radio.stories.ts'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-a11y'],
  framework: {
    name: '@storybook/web-components-vite',
    options: {},
  },
  staticDirs: ['../dist', '../src/assets', '../styles'],
  docs: {
    autodocs: true,
  },
};
