name: Mark stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - name: Close Stale Issues
      uses: actions/stale@v3.0.12
      with:
        # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
        repo-token:  ${{ secrets.GITHUB_TOKEN }}
        # The number of days old an issue can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
        days-before-stale: 100 # optional, default is 60
        # The number of days to wait to close an issue or pull request after it being marked stale. Set to -1 to never close stale issues.
        days-before-close: 50 # optional, default is 7
        stale-issue-message: 'This issue is stale because it has been open for 100 days with no activity. Remove stale label or comment or this will be closed in 100 days'
        stale-pr-message: 'This pull request is stale because it has been open for 100 days with no activity. Remove stale label or comment or this will be closed in 100 days'
        close-issue-message: 'This issue has been closed because it has been open for 150 days with no activity.'
        close-pr-message: 'This pull request has been closed because it has been open for 150 days with no activity.'
        exempt-issue-labels: 'bug'
